
services:
  mysql:
    image: mysql:8.0
    container_name: altalena_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword # Sostituisci con una password forte
      MYSQL_ROOT_HOST: "%"
    networks:
      altalena_net:
        aliases:
          - mysql.altalena.local
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: altalena_phpmyadmin
    environment:
      PMA_HOST: mysql.altalena.local
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    networks:
      altalena_net:
        aliases:
          - phpmyadmin.altalena.local
    restart: unless-stopped
    # Non esponiamo porte sul PC host, ci penserà Apache a fare da proxy

  apache_php:
    build:
      context: ./apache
    container_name: altalena_apache
    ports:
      - "80:80"
    networks:
      altalena_net:
        aliases:
          - apache.altalena.local
    volumes:
      - ./htdocs:/var/www/html
      - ./apache/vhosts.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - mysql
      - phpmyadmin
    restart: unless-stopped

networks:
  altalena_net:
    name: altalena_network

volumes:
  mysql_data:

